### ISSUE TITLE
"LUNI Documentation"

### ISSUE THREAD

**Issue by Knightoffaith** [wesleyd1124/PyLU#1]
Just a heads up - what you linked in the readme is not "LUNI documentation". It is documentation for the LU protocols and such, but it has no/only indirect affiliation with LUNI (which itself is long dead now). Just a heads up - I'd maybe just call it "LU Protocol Analysis Documentation" or something along those lines.

**Comment by Knightoffaith** [comment]
Also, if you opt to include Pyraknet directly in the source as opposed to via pip (I would suggest using pip) - at least provide credit.

**Comment by wesleyd1124** [comment]
I just changed the readme to be correct. As for using pyraknet in the source I'd perfer it that way because I have made some alterations to the files that somebody wouldn't have if the downloaded it via pip. I did however go ahead and credit him at the top of all the source files that belong to pyraknet.

**Comment by Knightoffaith** [comment]
FYI you could always subclass the things that come from pip, if that is a valid option for you

```python
import pyraknet

class Server(pyraknet.server.Server):'
    # Say I want to do something else in __init__
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        do_something_else()
```

**Comment by wesleyd1124** [comment]
Yeah that is probably a better option, I'll work on implementing my changes that way.
